language: swift

branches:
 only:
 - master
 
osx_image: xcode8.3 
xcode_project: spacegame.xcodeproj 
xcode_scheme: Spacegame 
xcode_sdk: iphonesimulator10.3 

script:
- xcodebuild clean build -project spacegame.xcodeproj -scheme Spacegame
